import { makeSpec, type RacquetModel } from "./utils";

export const mockRacquets: RacquetModel[] = [
  {
    modelId: "wilson-pro-staff-97",
    name: "Pro Staff 97",
    brand: "Wilson",
    versions: [
      {
        id: "wilson-pro-staff-97-2024",
        year: 2024,
        brand: "Wilson",
        specs: [
          makeSpec("headSize", "Head Size", 97, "in²"),
          makeSpec("weight", "Weight", 315, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 66, "RA"),
        ],
        price: 269.0,
      },
      {
        id: "wilson-pro-staff-97-2023",
        year: 2023,
        brand: "Wilson",
        specs: [
          makeSpec("headSize", "Head Size", 97, "in²"),
          makeSpec("weight", "Weight", 315, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 66, "RA"),
        ],
        price: 269.0,
      },
      {
        id: "wilson-pro-staff-97-2022",
        year: 2022,
        brand: "Wilson",
        specs: [
          makeSpec("headSize", "Head Size", 97, "in²"),
          makeSpec("weight", "Weight", 315, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.0, "cm"),
          makeSpec("stiffness", "Stiffness", 65, "RA"),
        ],
        price: 249.0,
      },
    ],
  },
  {
    modelId: "babolat-pure-drive",
    name: "Pure Drive",
    brand: "Babolat",
    versions: [
      {
        id: "babolat-pure-drive-2024",
        year: 2024,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 70, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "babolat-pure-drive-2023",
        year: 2023,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 71, "RA"),
        ],
        price: 245.0,
      },
      {
        id: "babolat-pure-drive-2022",
        year: 2022,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 71, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "wilson-blade-98-16x19",
    name: "Blade 98 16x19",
    brand: "Wilson",
    versions: [
      {
        id: "wilson-blade-98-16x19-2024",
        year: 2024,
        brand: "Wilson",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 64, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "wilson-blade-98-16x19-2023",
        year: 2023,
        brand: "Wilson",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 63, "RA"),
        ],
        price: 255.0,
      },
      {
        id: "wilson-blade-98-16x19-2022",
        year: 2022,
        brand: "Wilson",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 63, "RA"),
        ],
        price: 249.0,
      },
    ],
  },
  {
    modelId: "head-speed-mp",
    name: "Speed MP",
    brand: "Head",
    versions: [
      {
        id: "head-speed-mp-2024",
        year: 2024,
        brand: "Head",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 62, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "head-speed-mp-2023",
        year: 2023,
        brand: "Head",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 62, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "head-speed-mp-2022",
        year: 2022,
        brand: "Head",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 61, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "yonex-ezone-100",
    name: "Ezone 100",
    brand: "Yonex",
    versions: [
      {
        id: "yonex-ezone-100-2024",
        year: 2024,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.5, "cm"),
          makeSpec("stiffness", "Stiffness", 66, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "yonex-ezone-100-2023",
        year: 2023,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.4, "cm"),
          makeSpec("stiffness", "Stiffness", 65, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "yonex-ezone-100-2022",
        year: 2022,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.3, "cm"),
          makeSpec("stiffness", "Stiffness", 65, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "yonex-vcore-98",
    name: "VCORE 98",
    brand: "Yonex",
    versions: [
      {
        id: "yonex-vcore-98-2024",
        year: 2024,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 65, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "yonex-vcore-98-2023",
        year: 2023,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 65, "RA"),
        ],
        price: 255.0,
      },
      {
        id: "yonex-vcore-98-2022",
        year: 2022,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.6, "cm"),
          makeSpec("stiffness", "Stiffness", 64, "RA"),
        ],
        price: 245.0,
      },
    ],
  },
  {
    modelId: "head-radical-mp",
    name: "Radical MP",
    brand: "Head",
    versions: [
      {
        id: "head-radical-mp-2024",
        year: 2024,
        brand: "Head",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 66, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "head-radical-mp-2023",
        year: 2023,
        brand: "Head",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 65, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "head-radical-mp-2022",
        year: 2022,
        brand: "Head",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 64, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "babolat-pure-aero",
    name: "Pure Aero",
    brand: "Babolat",
    versions: [
      {
        id: "babolat-pure-aero-2024",
        year: 2024,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 67, "RA"),
        ],
        price: 269.0,
      },
      {
        id: "babolat-pure-aero-2023",
        year: 2023,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 67, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "babolat-pure-aero-2022",
        year: 2022,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 68, "RA"),
        ],
        price: 249.0,
      },
    ],
  },
  {
    modelId: "wilson-clash-100",
    name: "Clash 100",
    brand: "Wilson",
    versions: [
      {
        id: "wilson-clash-100-2024",
        year: 2024,
        brand: "Wilson",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 295, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.0, "cm"),
          makeSpec("stiffness", "Stiffness", 60, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "wilson-clash-100-2023",
        year: 2023,
        brand: "Wilson",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 295, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.0, "cm"),
          makeSpec("stiffness", "Stiffness", 60, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "wilson-clash-100-2022",
        year: 2022,
        brand: "Wilson",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 295, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 59, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "yonex-percept-97",
    name: "Percept 97",
    brand: "Yonex",
    versions: [
      {
        id: "yonex-percept-97-2024",
        year: 2024,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 97, "in²"),
          makeSpec("weight", "Weight", 320, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.0, "cm"),
          makeSpec("stiffness", "Stiffness", 62, "RA"),
        ],
        price: 269.0,
      },
      {
        id: "yonex-percept-97-2023",
        year: 2023,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 97, "in²"),
          makeSpec("weight", "Weight", 320, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.0, "cm"),
          makeSpec("stiffness", "Stiffness", 61, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "yonex-percept-97-2022",
        year: 2022,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 97, "in²"),
          makeSpec("weight", "Weight", 320, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 60, "RA"),
        ],
        price: 249.0,
      },
    ],
  },
  {
    modelId: "head-gravity-pro",
    name: "Gravity Pro",
    brand: "Head",
    versions: [
      {
        id: "head-gravity-pro-2024",
        year: 2024,
        brand: "Head",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 315, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 62, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "head-gravity-pro-2023",
        year: 2023,
        brand: "Head",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 315, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 61, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "head-gravity-pro-2022",
        year: 2022,
        brand: "Head",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 315, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 61, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "prince-tour-100p",
    name: "Tour 100P",
    brand: "Prince",
    versions: [
      {
        id: "prince-tour-100p-2024",
        year: 2024,
        brand: "Prince",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 62, "RA"),
        ],
        price: 239.0,
      },
      {
        id: "prince-tour-100p-2023",
        year: 2023,
        brand: "Prince",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 61, "RA"),
        ],
        price: 229.0,
      },
      {
        id: "prince-tour-100p-2022",
        year: 2022,
        brand: "Prince",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.6, "cm"),
          makeSpec("stiffness", "Stiffness", 60, "RA"),
        ],
        price: 219.0,
      },
    ],
  },
  {
    modelId: "babolat-pure-drive-98",
    name: "Pure Drive 98",
    brand: "Babolat",
    versions: [
      {
        id: "babolat-pure-drive-98-2024",
        year: 2024,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 68, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "babolat-pure-drive-98-2023",
        year: 2023,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 69, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "babolat-pure-drive-98-2022",
        year: 2022,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 32.0, "cm"),
          makeSpec("stiffness", "Stiffness", 68, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "babolat-pure-aero-98",
    name: "Pure Aero 98",
    brand: "Babolat",
    versions: [
      {
        id: "babolat-pure-aero-98-2024",
        year: 2024,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 65, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "babolat-pure-aero-98-2023",
        year: 2023,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 65, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "babolat-pure-aero-98-2022",
        year: 2022,
        brand: "Babolat",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 64, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "yonex-ezone-98",
    name: "Ezone 98",
    brand: "Yonex",
    versions: [
      {
        id: "yonex-ezone-98-2024",
        year: 2024,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.8, "cm"),
          makeSpec("stiffness", "Stiffness", 64, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "yonex-ezone-98-2023",
        year: 2023,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.8, "cm"),
          makeSpec("stiffness", "Stiffness", 63, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "yonex-ezone-98-2022",
        year: 2022,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 98, "in²"),
          makeSpec("weight", "Weight", 305, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.7, "cm"),
          makeSpec("stiffness", "Stiffness", 63, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "yonex-percept-100",
    name: "Percept 100",
    brand: "Yonex",
    versions: [
      {
        id: "yonex-percept-100-2024",
        year: 2024,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 62, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "yonex-percept-100-2023",
        year: 2023,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 61, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "yonex-percept-100-2022",
        year: 2022,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 100, "in²"),
          makeSpec("weight", "Weight", 300, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.6, "cm"),
          makeSpec("stiffness", "Stiffness", 61, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
  {
    modelId: "yonex-vcore-97",
    name: "VCORE 97",
    brand: "Yonex",
    versions: [
      {
        id: "yonex-vcore-97-2024",
        year: 2024,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 97, "in²"),
          makeSpec("weight", "Weight", 310, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 65, "RA"),
        ],
        price: 259.0,
      },
      {
        id: "yonex-vcore-97-2023",
        year: 2023,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 97, "in²"),
          makeSpec("weight", "Weight", 310, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.5, "cm"),
          makeSpec("stiffness", "Stiffness", 64, "RA"),
        ],
        price: 249.0,
      },
      {
        id: "yonex-vcore-97-2022",
        year: 2022,
        brand: "Yonex",
        specs: [
          makeSpec("headSize", "Head Size", 97, "in²"),
          makeSpec("weight", "Weight", 310, "g"),
          makeSpec("length", "Length", 27, "in"),
          makeSpec("balance", "Balance", 31.6, "cm"),
          makeSpec("stiffness", "Stiffness", 64, "RA"),
        ],
        price: 239.0,
      },
    ],
  },
];
